### PR TITLE
Added information to the readme.md file

### PR DESCRIPTION
**Pull request by GeorgeKerscher**
I added basic information to the readme.md file. What we are doing and how to join. Also included a link to SharePoint. I thought the first project is associated with Microsoft Word 365. 

I did not go into too much detail about our process.

I was not sure of a folder structure for the repo, so I just did nothing.

### CODE REVIEW

**Comment by brichwin** [comment]
Hi, George-

I have some ideas for the repo structure but figured we should discuss it in the meeting. I can mock up a version or two in a fork of the repo and someone could merge it in if we like one of them.

-Brian

From: George ***@***.***>
Sent: Monday, July 22, 2024 7:12 PM
To: daisy/math-a11y ***@***.***>
Cc: Richwine, Brian L ***@***.***>; Review requested ***@***.***>
Subject: [External] [daisy/math-a11y] Added information to the readme.md file (PR #3)

This message was sent from a non-IU address. Please exercise caution when clicking links or opening attachments from external sources.


I added basic information to the readme.md file. What we are doing and how to join. Also included a link to SharePoint. I thought the first project is associated with Microsoft Word 365.

I did not go into too much detail about our process.

I was not sure of a folder structure for the repo, so I just did nothing.

________________________________
You can view, comment on, or merge this pull request online at:

  https://github.com/daisy/math-a11y/pull/3

Commit Summary

  *   936cc0b<https://github.com/daisy/math-a11y/pull/3/commits/936cc0bc83cd54d600f95ecba3c71752311d88c3> Added information to the readme.md file

File Changes

(1 file<https://github.com/daisy/math-a11y/pull/3/files>)

  *   M README.md<https://github.com/daisy/math-a11y/pull/3/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5> (33)

Patch Links:

  *   https://github.com/daisy/math-a11y/pull/3.patch
  *   https://github.com/daisy/math-a11y/pull/3.diff

-

**Comment by brichwin** [comment]
Do we want to make the sharepoint folder link public to the whole world? Since anyone with the link can edit it seems like a risky proposition. Especially in the world of automated bots with malicious intent.

**Comment by GeorgeKerscher** [comment]
I removed the link to SharePoint. I also added the email address to make it visable.

If you want to propose a folder structure in a comment, that would be fine. Also, we can discuss it on a call.

**Comment by jkhurdan** [comment]
Just to confirm, it looks like you meant to change the readme.md on the main branch but instead created a new branch with the readme file. Was that what you had intended to do?

**Comment by GeorgeKerscher** [comment]
Hi,
 
The branch has not yet been merged. Once merged, it would replace the readme.md in main.
 
At least that is what I thought would happen.
 
Best
George

**Comment by mattgarrish** [comment]
> At least that is what I thought would happen.

Yes, that's how it works. If you work on a file in the main branch, any changes you commit are immediately live.

**Comment by brichwin** [comment]
Hi, George- I went ahead and handled the merge request and pulled in your changes. The README.md changes you made are live on the repo's default page now.

**Pull request merged**
